[workspace]
resolver = "2"
members = ["crates/markitdown", "crates/markitdown-mcp"]

[workspace.package]
version = "0.1.0"
edition = "2021"
rust-version = "1.85"
license = "MIT"
repository = "https://github.com/siosig/mcp-markitdown-rust"

[workspace.lints.clippy]
unwrap_used = "warn"
expect_used = "warn"

[profile.release]
opt-level = 3
