//! MCP server implementation. Exposes the single tool `convert_to_markdown`.
//! Conforms to contracts/convert_to_markdown.md.

use rmcp::handler::server::router::tool::ToolRouter;
use rmcp::handler::server::wrapper::Parameters;
use rmcp::model::{CallToolResult, ContentBlock, Implementation, ServerCapabilities, ServerInfo};
use rmcp::{schemars, tool, tool_handler, tool_router, ServerHandler};
use serde::Deserialize;

/// Input for the `convert_to_markdown` tool.
#[derive(Debug, Deserialize, schemars::JsonSchema)]
pub struct ConvertArgs {
    /// Resource URI. Supported schemes: http, https, file, data.
    pub uri: String,
}

/// The MCP server itself. Delegates conversion to the `markitdown` engine.
#[derive(Clone)]
pub struct MarkItDownServer {
    // The handler uses `Self::tool_router()` generated by `#[tool_router]`, so
    // the field itself is treated as unread by dead_code analysis. Retained as per the generated pattern.
    #[expect(
        dead_code,
        reason = "router is rebuilt via the generated tool_router() fn"
    )]
    tool_router: ToolRouter<Self>,
}

impl MarkItDownServer {
    /// Creates a server with the tool router initialized.
    pub fn new() -> Self {
        Self {
            tool_router: Self::tool_router(),
        }
    }
}

impl Default for MarkItDownServer {
    fn default() -> Self {
        Self::new()
    }
}

#[tool_router]
impl MarkItDownServer {
    /// Converts the document at the given URI to Markdown and returns it.
    ///
    /// Since conversion can be a heavy synchronous operation, it runs via `spawn_blocking`.
    /// On failure, returns a tool error with `isError` set (FR-009/010, SC-004).
    #[tool(
        name = "convert_to_markdown",
        description = "Convert a resource described by an http:, https:, file:, or data: URI to markdown."
    )]
    async fn convert_to_markdown(
        &self,
        Parameters(args): Parameters<ConvertArgs>,
    ) -> CallToolResult {
        let uri = args.uri;
        tracing::info!(uri = %uri, "convert_to_markdown");

        match tokio::task::spawn_blocking(move || markitdown::convert(&uri)).await {
            Ok(Ok(result)) => CallToolResult::success(vec![ContentBlock::text(result.markdown)]),
            Ok(Err(err)) => {
                tracing::warn!(error = %err, "conversion failed");
                CallToolResult::error(vec![ContentBlock::text(format!("Error: {err}"))])
            }
            Err(join_err) => {
                tracing::error!(error = %join_err, "conversion task panicked");
                CallToolResult::error(vec![ContentBlock::text(format!(
                    "Error: internal task failure: {join_err}"
                ))])
            }
        }
    }
}

#[tool_handler]
impl ServerHandler for MarkItDownServer {
    fn get_info(&self) -> ServerInfo {
        ServerInfo::new(ServerCapabilities::builder().enable_tools().build())
            .with_server_info(Implementation::new(
                env!("CARGO_PKG_NAME"),
                env!("CARGO_PKG_VERSION"),
            ))
            .with_instructions(
                "Convert a document at an http/https/file/data URI to Markdown \
                 via the convert_to_markdown tool.",
            )
    }
}
